apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    #kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-flaskapp
  name: todo-flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-flaskapp
  strategy: {}
  template:
    metadata:
      annotations:
        #kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: todo-flaskapp
    spec:
      initContainers:
        - name: flaskapp-init
          image: mvertes/alpine-mongo:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_HOST
              value: 10.97.187.133
            - name: MONGO_PORT
              value: "27017"
          command:
            - sh
            - -c
            - until mongo --eval 'db.runCommand("ping").ok' ${MONGO_HOST}:${MONGO_PORT}/test --quiet; do echo -e "waiting for MongoDB"; sleep 5; done; echo -e "MongoDB ready, starting ToDo-FlaskApp now";
      containers:
        - env:
            - name: FLASK_ENV
              value: development
            - name: MONGO_HOST
              value: 10.97.187.133
            - name: MONGO_PORT
              value: "27017"
            - name: PORT
              value: "5000"
          image: rihabbennour/flaskmango-app:latest
          imagePullPolicy: Always
          name: flask-app
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    #kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-flaskapp
  name: todo-flaskapp
spec:
  type: NodePort  # Set the service type to NodePort
  ports:
    - name: "http"
      port: 80  # Port exposed by the service
      targetPort: 5000  # Port on which the container is listening
      nodePort: 30023   # Specify the desired node port value
     
  selector:
    io.kompose.service: todo-flaskapp
status:
  loadBalancer: {}
